spec:
  destination:
    server: "https://api.np.cloudlet-dev.com:6443"
    namespace: "argocdod"
  source:
    repoURL: https://github.com/jatalocks/paas_cloudlet
    targetRevision: HEAD
  project: default
  
argocdNamespace: argocd
